theme: jekyll-theme-minimal
logo: https://github.com/mevCJ/logo-packer/blob/gh-pages/assets/logo.jpg?raw=true
google_analytics: G-2NVL54S6KC
title: Logo variations and exports in minutes | Logo Packer
description: Adobe Illustrator extension that generates multiple logo variation and export them automatically
